spring:
  application:
    name: micro-sender
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always